language: python
# Enable python 3.7
dist: xenial

sudo: false

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy"

addons:
  apt:
    packages:
    # Dependencies for pycurl compilation
    - libcurl4-openssl-dev
    - libssl-dev

install:
  - pip install tox-travis
script:
  - tox
after_success:
  - coverage combine
  - coverage report
  - pip install codecov
  - codecov
